import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Movies from '../components/Movies'
import Nav from '../components/Nav'
import request from '../utils/request'

export default function Home({ results }) {
  console.log(results);
  return (
    <div >
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />

      {/* Result */}
      <Movies results={results} />
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const requests = await fetch(`https://api.themoviedb.org/3${request[genre]?.url ||
    request.fetchTrending.url} `).then(res => res.json());
  return {
    props: {
      results: requests.results,
    }
  }



}
